server
{
	listen	127.0.0.1:8081;
	listen	127.0.0.1:8087;

	server_name	localhost:8081;

	root	/var/www/html;
	index	index.html;	

	error_pages	404 /var/www/html/errors/404.html;
	# error_pages	500 502 503 504 /50x.html;

	client_max_body_size	10000000;

	location / {
		index	index.html;
		autoindex	off;
		methods	GET;
	}


	# location /cgi-bin/ {
	# 	root	/var/www/cgi-bin/test.py;
	# 	cgi_path	/usr/bin/python3;
	# }

	location /php {
		root	/var/www/php;
		index	index.php;
		cgi_extension	.php;
		cgi_path	/usr/bin/php-cgi;
		methods	GET POST;
	}

	location /py {
		root	/var/www/py;
		index	index.py;
		cgi_extension	.py;
		cgi_path	/usr/bin/python3;
		methods	GET;
	}

	location /media/ {
		root	/var/www/media;
		autoindex	on;
		methods	GET DELETE;
	}

	location /uploads {
		root	/var/www/uploads;
		index	upload.html;
		upload_enable	on;
		upload_store	/var/www/uploadstore;
		cgi_path	/usr/bin/php-cgi;
		methods	GET POST;
	}

	location /uploadstore {
    root            /var/www/uploadstore;
    autoindex       off;
    methods         GET DELETE;
	}

	location /redirect-me {
		return 302 /media/;
	}

}

server
{
	listen	127.0.0.1:8085;
	listen	127.0.0.1:8086;

	server_name	localhost:8086;

	root	/var/www/html;
	index	index.html;	

	error_pages	404 /var/www/html/errors/404.html;
	# error_pages	500 502 503 504 /50x.html;

	client_max_body_size	10000000;

	location / {
		index	index.html;
		autoindex	off;
		methods	GET;
	}


	# location /cgi-bin/ {
	# 	root	/var/www/cgi-bin/test.py;
	# 	cgi_path	/usr/bin/python3;
	# }

	location /php {
		root	/var/www/php;
		index	index.php;
		cgi_extension	.php;
		cgi_path	/usr/bin/php-cgi;
		methods	GET POST;
	}

	location /py {
		root	/var/www/py;
		index	index.py;
		cgi_extension	.py;
		cgi_path	/usr/bin/python3;
		methods	GET;
	}

	location /media/ {
		root	/var/www/media;
		autoindex	on;
		methods	GET DELETE;
	}

	location /uploads {
		root	/var/www/uploads;
		index	upload.html;
		upload_enable	on;
		upload_store	/var/www/uploadstore;
		cgi_path	/usr/bin/php-cgi;
		methods	GET POST;
	}

	location /uploadstore {
    root            /var/www/uploadstore;
    autoindex       off;
    methods         GET DELETE;
	}

	location /redirect-me {
		return 302 /media/;
	}

}
