server
{
	listen	127.0.0.1:8888;
	listen	127.0.0.1:8080;
	listen	127.0.0.1:9000;

	server_name	localhost:9000;

	root	/var/www/html;
	index	index.html;	

	error_pages	404 /var/www/html/errors/404.html;
	# error_pages	500 502 503 504 /50x.html;

	client_max_body_size	100000000;

	location / {
		index	get.html;
		autoindex	off;
		methods	GET POST;
	}

	location /php {
		root	/var/www/php;
		index	index.php;
		cgi_extension	.php;
		cgi_path	/usr/bin/php-cgi;
		methods	GET POST;
	}

	location /py {
		root	/var/www/py;
		index	index.py;
		cgi_extension	.py;
		cgi_path	/usr/bin/python3;
		methods	GET POST;
	}

	location /media/ {
		root	/var/www/media;
		autoindex	on;
		methods	GET DELETE;
	}

	location /uploads {
		root	/var/www/uploads;
		index	upload.html;
		upload_enable	on;
		upload_store	/var/www/py;
		cgi_path	/usr/bin/php-cgi;
		methods	GET POST;
	}

	location /uploadstore {
    root            /var/www/uploadstore;
    autoindex       off;
    methods         GET;
	}

	location /redirect-me {
		return 302 /media/;
	}

}

server
{

	listen	127.0.0.1:9000;
	listen	127.0.0.1:8080;

	server_name	localhost:9000;

	root	/var/www/html;
	index	index.html;	

	error_pages	404 /var/www/html/errors/404.html;

	client_max_body_size	100000000;

	# location / {
	# 	index	index.html;
	# 	autoindex	off;
	# 	methods	GET;
	# }

	location /php {
		root	/var/www/php;
		index	index.php;
		cgi_extension	.php;
		cgi_path	/usr/bin/php-cgi;
		methods	GET POST;
	}

	location /py {
		root	/var/www/py;
		index	index.py;
		cgi_extension	.py;
		cgi_path	/usr/bin/python3;
		methods	GET;
	}

	location /media/ {
		root	/var/www/media;
		autoindex	on;
		methods	GET DELETE;
	}

	location /redirect-me {
		return 302 /media/;
	}


	location /cgi-bin {
		root            /var/www/cgi-bin;
		cgi_extension   .py;
		cgi_path        /usr/bin/python3;
		methods         GET POST;
	}

	location /uploads {
	root	/var/www/uploads;
	index	upload.html;
	upload_enable	on;
	upload_store	/var/www/uploadstore;
	cgi_path	/usr/bin/php-cgi;
	methods	GET POST;
	}

	location /uploadstore {
    root            /var/www/uploadstore;
    autoindex       off;
    methods         GET DELETE;
	}

}


server
{

	listen	127.0.0.1:6660;
	listen	127.0.0.1:8080;

	server_name	localhost:6660;

	root	/var/www/html;
	index	index.html;	

	error_pages	404 /var/www/html/errors/404.html;

	client_max_body_size	100000000;

	location / {
		index	get.html;
		autoindex	off;
		methods	GET;
	}

	location /media/ {
		root	/var/www/media;
		autoindex	on;
		methods	GET DELETE;
	}

	location /redirect-me {
		return 302 /media/;
	}

	location /uploads {
	root	/var/www/uploads;
	index	upload.html;
	upload_enable	on;
	upload_store	/var/www/uploadstore;
	cgi_path	/usr/bin/php-cgi;
	methods	GET POST;
	}

	location /uploadstore {
    root            /var/www/uploadstore;
    autoindex       off;
    methods         GET DELETE;
	}

}

